---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: nginx-ingress
  name: nginx-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: nginx-ingress-lb
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2proxy
  name: oauth2proxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: oauth2proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2proxy
  name: oauth2-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: oauth2proxy
    spec:
      containers:
      - name: oauth2proxy
        image: docker.io/colemickens/oauth2_proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: 'TENANT_ID'
          valueFrom:
            secretKeyRef:
              name: 'azure-ci'
              key: 'TENANT_ID'
        - name: 'OIDC_CLIENT_ID'
          valueFrom:
            secretKeyRef:
              name: 'azure-ci'
              key: 'OIDC_CLIENT_ID'
        - name: 'OIDC_CLIENT_SECRET'
          valueFrom:
            secretKeyRef:
              name: 'azure-ci'
              key: 'OIDC_CLIENT_SECRET'
        command:
        - oauth2_proxy
        - --upstream=http://default-http-backend
        - --email-domain=microsoft.com
        - --provider=oidc
        - --client-id=$(OIDC_CLIENT_ID)
        - --client-secret=$(OIDC_CLIENT_SECRET)
        - --oidc-discovery-url=https://login.microsoftonline.com/$(TENANT_ID)
        - --cookie-domain=.azure-containers.io
        - --redirect-url=https://test1.prow.azure-containers.io/oauth2/callback/
        - --cookie-secret="secret-chocolate-chip-cookie"
        - --cookie-secure=false
        - --http-address=0.0.0.0:80
