#registry: gcr.io/k8s-infra
registry: docker.io/colemickens
#email: XYZ@ABC
email: cole.mickens@gmail.com
versions:
  hook: 0.83
  line: 0.74
  sinker: 0.4
  deck: 0.16
  splicer: 0.13
  marque: 0.1
  tot: 0.0
  crier: 0.5
urls:
  deck: prow.ci.azure-containers.io
  # nameOveride?
  #
secrets:
  githubToken: foo
